apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akeyless-hello
spec:
  provider: akeyless
  secretObjects:              # add this field if you want to sync as k8s secret otherwise ignore this.
  - data:
    - key: test.crt        # data field to populate
      objectName: certificate       # filename from parameters section 
    secretName: test-certificate     # name of the Kubernetes Secret object
    type: Opaque
  parameters:
    akeylessGatewayURL: "https://api.akeyless.io"
    akeylessAccessID: "p-g0xee6qbot4zam"
    akeylessAccessKey: "4Zj0ukDbr22u6qkacrusmXIzRlkWlhGdEVB+BJ038x0="
    akeylessAccessType: "access_key"
    objects: | 
      - secretPath: "/test-crt"
        objectType: cert
        fileName: "certificate"
