apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akeyless-test
spec:
  provider: akeyless
  parameters:
    akeylessGatewayURL: "https://api.akeyless.io"
    akeylessAccessID: "p-g0xee6qbot4zam"
    akeylessAccessKey: "4Zj0ukDbr22u6qkacrusmXIzRlkWlhGdEVB+BJ038x0="
    akeylessAccessType: "access_key"
    objects: | 
      - secretPath: "/username"
        fileName: "username"
