apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akeyless-test
spec:
  provider: akeyless
  secretObjects:              # add this field if you want to sync as k8s secret otherwise ignore this.
  - data:
    - key: username123        # data field to populate
      objectName: hello       # filename from parameters section 
    secretName: foosecret     # name of the Kubernetes Secret object
    type: Opaque              # type of the Kubernetes Secret object e.g. Opaque, kubernetes.io/tls
  parameters:
    akeylessGatewayURL: "https://api.akeyless.io"
    akeylessAccessID: "p-g0xee6qbot4zam"
    akeylessAccessKey: "4Zj0ukDbr22u6qkacrusmXIzRlkWlhGdEVB+BJ038x0="
    akeylessAccessType: "access_key"
    objects: | 
      - secretPath: "/username"
        fileName: "hello"
